### ISSUE TITLE
Run in the background for automation

### ISSUE THREAD

**Issue by indfnzo** [skoshy/CopyTransparentImages#1]
Hi!

As it currently is, I can't imagine having to run the executable every time I need transparent PNG. That would be counter-productive, since the entire goal is to prevent myself from having to do anything else other than copy and paste into image-editing programs out of the box.

Would it be possible instead to build this as a long-running process that detects clipboard events and automatically reformat PNG images with alpha?

It would be possible if we can detect if the data in the clipboard is in fact a PNG image.

---

For the meantime, as a workaround, I believe I can just map a global shortcut to run this exec so I can do something like `Ctrl+v` + `Ctrl+Shift+v` to transform the copied PNG.

**Comment by skoshy** [comment]
Hi @jemhuntr ,

Yes I agree that there should be something that automatically does this. Currently, I use an AutoHotkey script to automatically run this program everytime the clipboard is changed. I can upload it to the repo if you'd like to check it out. It's been working for me pretty well!

Stefan

**Comment by indfnzo** [comment]
Yup, I've guessed the same. The first thought that came to mind was use an AHK script to map the executable to a global key. Didn't know you could run it whenever the clipboard is changed.

Please do upload it. I believe users (as myself) would find that useful as well :)

**Comment by skoshy** [comment]
Sorry for the late reply, but you can use a simple Autohotkey script like this

```ahk
#Persistent

OnClipboardChange:
SetTitleMatchMode, 2
If (A_EventInfo = 2 and WinActive("ahk_class Chrome_WidgetWin_1"))
{
  RunWait, %A_ScriptDir%\CopyTransparentImage\CopyTransparentImage.exe, %A_WorkingDir%, Hide
  ToolTip Converted copied image to PNG
  Sleep 500
  Tooltip
}
return
```

This will make it so anytime the clipboard is changed and Chrome is the active window, it'll run the CopyTransparentImage exe.

However, I'm archiving this repo, as it looks like copying transparent images works from Chrome and Firefox on Windows 11 by default.
