### ISSUE TITLE
Doesnt seem to work?

### ISSUE THREAD

**Issue by slayermaster** [skoshy/CopyTransparentImages#4]
I'm on Windows 10 2004, tried using both Firefox and new Edge. Still pastes with black background.

**Comment by wad11656** [comment]
It says "Chrome" all over the Readme, once on the Release page, and the repo is even tagged with the `chrome` tag. i.e., it works as intended.

**Comment by liamb13** [comment]
@wad11656 any plans for Firefox support?

**Comment by skoshy** [comment]
@liamb13 I haven't had any need for this script in a while, as it looks like copying/pasting transparent images works without it.

Even with Firefox it looks like it works. This is on Windows 11.

![2022-03-30 23-59-45](https://user-images.githubusercontent.com/369825/160974038-4bc615c8-9470-4eee-9bd2-55569e924f73.gif)

Same with Chrome. I tested pasting transparent images into GIMP and Powerpoint, both worked just fine.

I'm going to archive this repo, but anyone can feel free to fork it if they need it for any reason.
